"""Session — the central white-box conversation manager.

A Session is the source of truth for an LLM conversation. It stores typed
messages, provides structured query views (turns, tool calls, stats), and
emits events so observers (TUI, viz, logging) can react to state changes.

Messages are stored as a flat list internally (for API compatibility with
the existing Engine), but exposed through typed accessors.

Usage::

    session = Session()
    session.add_user_message("Read engine.py")
    session.add_assistant_message([
        TextBlock(text="Let me read that file."),
        ToolCallBlock(tool_use_id="tu_1", name="Read",
                       input={"file_path": "engine.py"}),
    ])
    # ... tool executes ...
    session.update_tool_call("tu_1", status=ToolStatus.COMPLETED,
                             result=ToolResult(tool_use_id="tu_1",
                                                content="...file contents..."))
    for turn in session.turns:
        print(turn.user_message.text, "→", turn.final_text)
"""

from __future__ import annotations

from typing import Any

from session.events import (
    EVENT_MESSAGE_ADDED,
    EVENT_SESSION_CLEARED,
    EVENT_TOOL_CALL_COMPLETED,
    EVENT_TOOL_CALL_STARTED,
    EVENT_TURN_COMPLETED,
    EventBus,
)
from session.models import (
    AssistantMessage,
    SessionStats,
    TextBlock,
    ToolCallBlock,
    ToolResult,
    ToolStatus,
    Turn,
    UserMessage,
    _now_ms,
)


class Session:
    """White-box conversation session.

    Stores typed messages, provides structured views, emits events.

    Parameters
    ----------
    session_id : str | None
        Identifier for this session. Autogenerated if omitted.
    """

    def __init__(self, session_id: str | None = None) -> None:
        self.session_id = session_id or _new_session_id()
        self.created_at: int = _now_ms()

        # Flat message list — the source of truth
        self._messages: list[UserMessage | AssistantMessage] = []

        # Tool-call index: tool_use_id → (message_index, ToolCallBlock)
        self._tool_index: dict[str, tuple[int, ToolCallBlock]] = {}

        # Tool results: tool_use_id → ToolResult
        self._tool_results: dict[str, ToolResult] = {}

        # Event bus for observers
        self.events = EventBus()

        # Turn tracking
        self._current_turn_start: int | None = None

    # ------------------------------------------------------------------
    # Message management
    # ------------------------------------------------------------------

    def add_user_message(self, content: str | list[dict[str, Any]]) -> UserMessage:
        """Append a user message. Starts a new turn."""
        msg = UserMessage(content=content)
        self._messages.append(msg)
        self._current_turn_start = len(self._messages) - 1
        self.events.emit(EVENT_MESSAGE_ADDED, self, msg)
        return msg

    def add_assistant_message(
        self,
        content: list[TextBlock | ToolCallBlock],
        usage: dict[str, int] | None = None,
    ) -> AssistantMessage:
        """Append an assistant message.

        Tool-call blocks are automatically indexed for later lookup via
        ``update_tool_call()``.
        """
        msg = AssistantMessage(
            content=list(content),
            usage=dict(usage or {}),
        )
        idx = len(self._messages)
        self._messages.append(msg)

        # Index tool calls
        for block in msg.tool_calls:
            self._tool_index[block.tool_use_id] = (idx, block)

        self.events.emit(EVENT_MESSAGE_ADDED, self, msg)

        # Detect end-of-turn: assistant message with no tool calls
        if not msg.has_tool_calls and self._current_turn_start is not None:
            self.events.emit(EVENT_TURN_COMPLETED, self, self._current_turn)

        return msg

    def add_tool_result(
        self,
        tool_use_id: str,
        content: str,
        is_error: bool = False,
    ) -> ToolResult:
        """Record a tool execution result and link it to the originating ToolCallBlock."""
        result = ToolResult(
            tool_use_id=tool_use_id,
            content=content,
            is_error=is_error,
        )
        self._tool_results[tool_use_id] = result

        # Update the indexed tool call block
        entry = self._tool_index.get(tool_use_id)
        if entry is not None:
            _, block = entry
            block.result = result

        return result

    def update_tool_call(
        self,
        tool_use_id: str,
        *,
        status: str | None = None,
        result: ToolResult | None = None,
        started_at: int | None = None,
        completed_at: int | None = None,
    ) -> ToolCallBlock | None:
        """Update lifecycle fields on a tool-call block and emit events.

        Returns the updated block, or None if tool_use_id is unknown.
        """
        entry = self._tool_index.get(tool_use_id)
        if entry is None:
            return None

        _, block = entry
        old_status = block.status

        if status is not None:
            block.status = status
        if result is not None:
            block.result = result
            self._tool_results[tool_use_id] = result
        if started_at is not None:
            block.started_at = started_at
        if completed_at is not None:
            block.completed_at = completed_at

        # Emit transition events
        if status == ToolStatus.EXECUTING and old_status != ToolStatus.EXECUTING:
            if block.started_at is None:
                block.started_at = _now_ms()
            self.events.emit(EVENT_TOOL_CALL_STARTED, self, block)

        if status in (ToolStatus.COMPLETED, ToolStatus.ERRORED) and not block.is_terminal:
            # already set by status assignment above — detect was not terminal before
            pass

        if block.is_terminal and old_status not in (ToolStatus.COMPLETED, ToolStatus.ERRORED):
            if block.completed_at is None:
                block.completed_at = _now_ms()
            self.events.emit(EVENT_TOOL_CALL_COMPLETED, self, block)

        return block

    # ------------------------------------------------------------------
    # Tool call execution helpers
    # ------------------------------------------------------------------

    def start_tool_call(self, tool_use_id: str) -> ToolCallBlock | None:
        """Mark a tool call as executing (convenience wrapper)."""
        return self.update_tool_call(
            tool_use_id,
            status=ToolStatus.EXECUTING,
            started_at=_now_ms(),
        )

    def complete_tool_call(
        self,
        tool_use_id: str,
        result: ToolResult,
    ) -> ToolCallBlock | None:
        """Mark a tool call as completed (convenience wrapper)."""
        status = ToolStatus.ERRORED if result.is_error else ToolStatus.COMPLETED
        return self.update_tool_call(
            tool_use_id,
            status=status,
            result=result,
            completed_at=_now_ms(),
        )

    # ------------------------------------------------------------------
    # Query / white-box access
    # ------------------------------------------------------------------

    @property
    def messages(self) -> list[UserMessage | AssistantMessage]:
        """Return the flat typed message list."""
        return list(self._messages)

    @property
    def turns(self) -> list[Turn]:
        """Assemble messages into Turn objects.

        A turn starts with a UserMessage and includes all subsequent
        AssistantMessages until the next UserMessage.
        """
        result: list[Turn] = []
        current: Turn | None = None

        for msg in self._messages:
            if isinstance(msg, UserMessage):
                current = Turn(user_message=msg)
                result.append(current)
            elif isinstance(msg, AssistantMessage) and current is not None:
                current.assistant_messages.append(msg)
                # Collect tool results referenced by this message's tool calls
                for tc in msg.tool_calls:
                    tr = self._tool_results.get(tc.tool_use_id)
                    if tr is not None:
                        current.tool_results.append(tr)

        return result

    @property
    def tool_calls(self) -> list[ToolCallBlock]:
        """Return all tool-call blocks across the session, in order."""
        tcs: list[ToolCallBlock] = []
        for msg in self._messages:
            if isinstance(msg, AssistantMessage):
                tcs.extend(msg.tool_calls)
        return tcs

    def get_tool_call(self, tool_use_id: str) -> ToolCallBlock | None:
        """Look up a tool-call block by its tool_use_id."""
        entry = self._tool_index.get(tool_use_id)
        return entry[1] if entry else None

    def get_tool_result(self, tool_use_id: str) -> ToolResult | None:
        """Look up a tool result by tool_use_id."""
        return self._tool_results.get(tool_use_id)

    @property
    def last_message(self) -> UserMessage | AssistantMessage | None:
        return self._messages[-1] if self._messages else None

    @property
    def last_assistant_text(self) -> str:
        """Extract text from the most recent assistant message."""
        for msg in reversed(self._messages):
            if isinstance(msg, AssistantMessage):
                return msg.text
        return ""

    @property
    def _current_turn(self) -> Turn | None:
        """The turn currently being built (the last one in the list)."""
        t = self.turns
        return t[-1] if t else None

    # ------------------------------------------------------------------
    # Stats
    # ------------------------------------------------------------------

    def stats(self) -> SessionStats:
        """Compute aggregate session statistics."""
        tcs = self.tool_calls
        completed = [t for t in tcs if t.status == ToolStatus.COMPLETED]
        errored = [t for t in tcs if t.status == ToolStatus.ERRORED]
        latencies = [
            t.elapsed_ms for t in tcs
            if t.elapsed_ms is not None and t.status == ToolStatus.COMPLETED
        ]

        total_input = 0
        total_output = 0
        for msg in self._messages:
            if isinstance(msg, AssistantMessage):
                total_input += msg.usage.get("input_tokens", 0)
                total_output += msg.usage.get("output_tokens", 0)

        turns_list = self.turns
        total_dur = 0
        for t in turns_list:
            if t.elapsed_ms:
                total_dur += t.elapsed_ms

        return SessionStats(
            total_turns=len(turns_list),
            total_messages=len(self._messages),
            total_tool_calls=len(tcs),
            tool_calls_completed=len(completed),
            tool_calls_errored=len(errored),
            total_input_tokens=total_input,
            total_output_tokens=total_output,
            total_duration_ms=total_dur,
            avg_tool_latency_ms=sum(latencies) / len(latencies) if latencies else 0.0,
        )

    # ------------------------------------------------------------------
    # White-box editing — correct AI mistakes
    # ------------------------------------------------------------------

    def edit_message(self, message_id: str, new_content: str | list) -> bool:
        """Edit a message's content by its id.

        Returns True if the message was found and edited.
        """
        for msg in self._messages:
            if msg.id == message_id:
                if isinstance(msg, UserMessage):
                    msg.content = new_content if isinstance(new_content, str) else new_content
                elif isinstance(msg, AssistantMessage):
                    # Replace text: clear existing TextBlocks, add new one(s)
                    msg.content = [b for b in msg.content if not isinstance(b, TextBlock)]
                    if isinstance(new_content, str):
                        msg.content.insert(0, TextBlock(text=new_content))
                    elif isinstance(new_content, list):
                        # Only accept valid content blocks
                        valid = [b for b in new_content if isinstance(b, (TextBlock, ToolCallBlock))]
                        msg.content = valid + msg.content
                return True
        return False

    def delete_message(self, message_id: str) -> int:
        """Delete a message and cascade-remove its tool calls/results.

        Returns the number of messages removed (0 or 1).
        """
        for i, msg in enumerate(self._messages):
            if msg.id == message_id:
                # Cascade: remove tool calls from index and results
                if isinstance(msg, AssistantMessage):
                    for tc in msg.tool_calls:
                        self._tool_index.pop(tc.tool_use_id, None)
                        self._tool_results.pop(tc.tool_use_id, None)
                # Remove the message itself
                self._messages.pop(i)
                # Re-index remaining tool_index entries (message indices shifted)
                stale = []
                for tid, (idx, block) in self._tool_index.items():
                    if idx > i:
                        stale.append((tid, idx))
                for tid, old_idx in stale:
                    self._tool_index[tid] = (old_idx - 1, self._tool_index[tid][1])
                return 1
        return 0

    def retry_tool_call(self, tool_use_id: str) -> bool:
        """Reset a tool call to pending state so it can be re-executed.

        Clears the old result and timing. Returns True if found.
        """
        entry = self._tool_index.get(tool_use_id)
        if entry is None:
            return False
        _, block = entry
        block.status = ToolStatus.PENDING
        block.started_at = None
        block.completed_at = None
        block.result = None
        self._tool_results.pop(tool_use_id, None)
        return True

    def rollback_to(self, message_id: str) -> int:
        """Truncate the session to before (excluding) the given message.

        All messages from *message_id* onward are removed, along with their
        tool calls and results. Returns the number of messages removed.
        """
        cutoff = None
        for i, msg in enumerate(self._messages):
            if msg.id == message_id:
                cutoff = i
                break
        if cutoff is None:
            return 0

        removed = self._messages[cutoff:]
        self._messages = self._messages[:cutoff]

        # Clean up tool index and results for removed messages
        for msg in removed:
            if isinstance(msg, AssistantMessage):
                for tc in msg.tool_calls:
                    self._tool_index.pop(tc.tool_use_id, None)
                    self._tool_results.pop(tc.tool_use_id, None)

        # Reset turn tracking
        self._current_turn_start = None

        return len(removed)

    def inject_correction(self, text: str) -> UserMessage:
        """Inject a correction message into the conversation.

        This is a normal user message tagged as a correction — it appears in
        the chat as a new user turn that guides the AI back on track.
        """
        msg = UserMessage(content=text)
        msg.meta["correction"] = True
        self._messages.append(msg)
        self._current_turn_start = len(self._messages) - 1
        self.events.emit(EVENT_MESSAGE_ADDED, self, msg)
        return msg

    # ------------------------------------------------------------------
    # Compatibility: convert to/from the existing Engine dict format
    # ------------------------------------------------------------------

    def to_dicts(self) -> list[dict[str, Any]]:
        """Export messages as the ``list[dict]`` format used by Engine._messages.

        This allows the white-box Session to feed the existing Engine without
        changing Engine's internals.
        """
        out: list[dict[str, Any]] = []
        for msg in self._messages:
            if isinstance(msg, UserMessage):
                # Distinguish: plain text vs tool_result blocks
                if isinstance(msg.content, list):
                    # Check if it's tool results
                    blocks = []
                    for block in msg.content:
                        if isinstance(block, dict) and block.get("type") == "tool_result":
                            blocks.append(block)
                        else:
                            blocks.append(block)
                    out.append({"role": "user", "content": blocks})
                else:
                    out.append({"role": "user", "content": msg.content})
            elif isinstance(msg, AssistantMessage):
                blocks: list[dict[str, Any]] = []
                for block in msg.content:
                    if isinstance(block, TextBlock):
                        blocks.append({"type": "text", "text": block.text})
                    elif isinstance(block, ToolCallBlock):
                        blocks.append({
                            "type": "tool_use",
                            "id": block.tool_use_id,
                            "name": block.name,
                            "input": block.input,
                        })
                out.append({"role": "assistant", "content": blocks})
        return out

    @classmethod
    def from_dicts(
        cls,
        messages: list[dict[str, Any]],
        session_id: str | None = None,
    ) -> Session:
        """Build a Session from Engine-style ``list[dict]`` messages."""
        session = cls(session_id=session_id)
        for msg in messages:
            role = msg.get("role", "")
            content = msg.get("content", "")

            if role == "user":
                if isinstance(content, list):
                    # Check for tool_result blocks → treat as a tool-result batch
                    for block in content:
                        if isinstance(block, dict) and block.get("type") == "tool_result":
                            session.add_tool_result(
                                tool_use_id=block.get("tool_use_id", ""),
                                content=block.get("content", ""),
                                is_error=block.get("is_error", False),
                            )
                    # Still add as a user message for context
                session.add_user_message(content)

            elif role == "assistant":
                blocks: list[TextBlock | ToolCallBlock] = []
                usage_dict: dict[str, int] = {}
                if isinstance(content, list):
                    for block in content:
                        if isinstance(block, dict):
                            btype = block.get("type", "")
                            if btype == "text":
                                blocks.append(TextBlock(text=block.get("text", "")))
                            elif btype == "tool_use":
                                blocks.append(ToolCallBlock(
                                    tool_use_id=block.get("id", ""),
                                    name=block.get("name", ""),
                                    input=block.get("input", {}),
                                ))
                session.add_assistant_message(blocks, usage=usage_dict)

        return session

    # ------------------------------------------------------------------
    # Lifecycle
    # ------------------------------------------------------------------

    def clear(self) -> None:
        """Reset the session to empty state."""
        self._messages.clear()
        self._tool_index.clear()
        self._tool_results.clear()
        self._current_turn_start = None
        self.events.emit(EVENT_SESSION_CLEARED, self)

    def __len__(self) -> int:
        return len(self._messages)

    def __repr__(self) -> str:
        s = self.stats()
        return (
            f"Session({self.session_id[:8]}…, "
            f"turns={s.total_turns}, msgs={s.total_messages}, "
            f"tools={s.total_tool_calls})"
        )


def _new_session_id() -> str:
    import uuid
    return uuid.uuid4().hex[:16]
